### ISSUE TITLE
FileZilla Server stopping after a while of running?

### ISSUE THREAD

**Issue by CosmicHikari** [zedfoxus/filezilla-server#1]
Hey, I know this is probably not commonly heard of due to little results on google search, but after letting filezilla run for like 25 mins or 30 mins it automatically stops and the GUI says failed to connect to server, to fix (only for it to crash another 30 mins later) I have to run start filezilla server as admin, any reason why?

Im using windows 10, 8GB of RAM with an AMD FX 6350. 

Edit: Is it possible I may just have to run the GUI as admin? Nevermind, didn't work anyway.

**Comment by zedfoxus** [comment]
Hi @Dovahkiin-Warrior, the official support is available here: https://trac.filezilla-project.org/. I just maintain a git clone of FileZilla's SVN repository.
